version: '3.8'

#services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres_db
#    restart: always
#    environment:
#      POSTGRES_DB: movies
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5434:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"